Dockerfile, README: handle data directory ownership
Currently, when Elixir is ran in Docker, it doesn't handle ownership
of indexed repositories well - projects may show up in the sidebar,
but Git (and Elixir) may refuse to read the repositories. Usually,
because the repositories are owned by root.

Currently, the most common solution was to directly apply the
recommendation from Git's error message:

 git config --system --add safe.directory $repo_dir

However, there are some problems with that solution:
* This command needs to be ran separately for each project
* Git is still ran as root. Default Docker configuration does not map
  the root user into anything else. Therefore running things as root in
  Docker is generally not recommended (although it isn't always clear
  what exactly is dangerous about it).

This commit solves that by changing:
* The Docker tutorial to recommend running update scripts as www-data
* Indexing scripts to complain if ran as root
* Dockerfile to mark /srv/elixir-data as a volume, which should improve
  ownership situation if volumes (not bind mounts, like in the tutorial)
  are used to store indexing data.

This approach isn't perfect, as now data directories are writeable by
Elixir. To have everything + read only repos, I think another another user,
just for updates, would be needed. But I think this would complicate things
a lot, with little extra security benefit.

Note that this still doesn't work with rootless/uid mapped Docker well. But
since the default in most distributions seems to be to not use uid maps in
Docker, I assume anyone who has uid map set up will know what to do to fix
the permissions manually (by changing bind mounted directory ownership
to uidmapped www-data).

diff --git a/utils/update-elixir-data b/utils/update-elixir-data
--- a/utils/update-elixir-data
+++ b/utils/update-elixir-data
@@ -25,6 +25,13 @@ if [ -z "$LXR_PROJ_DIR" ]; then
     exit 1
 fi
 
+if [ `whoami` = 'root' ] && [ "$ELIXIR_RUN_AS_ROOT" != '1' ]; then
+    echo "ERROR: it's not recommended to run Elixir indexing jobs as root."
+    echo "This may cause git to complain about directory ownership on web requests"
+    echo "To continue running as root, set ELIXIR_RUN_AS_ROOT environment variable to 1."
+    exit 1
+fi
+
 for dir_name in $LXR_PROJ_DIR/*; do
     echo "Processing project $dir_name ..."
     export LXR_DATA_DIR=$dir_name/data
